description "Kubu Core Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env KUBUD_BIN="/usr/bin/kubud"
env KUBUD_USER="kubu"
env KUBUD_GROUP="kubu"
env KUBUD_PIDDIR="/var/run/kubud"
# upstart can't handle variables constructed with other variables
env KUBUD_PIDFILE="/var/run/kubud/kubud.pid"
env KUBUD_CONFIGFILE="/etc/kubu/kubu.conf"
env KUBUD_DATADIR="/var/lib/kubud"

expect fork

respawn
respawn limit 5 120
kill timeout 60

pre-start script
    # this will catch non-existent config files
    # kubud will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$KUBUD_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run kubud."
        echo "The setting must appear in $KUBUD_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following"
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is also recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"Kubu Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$KUBUD_PIDDIR"
    chmod 0755 "$KUBUD_PIDDIR"
    chown $KUBUD_USER:$KUBUD_GROUP "$KUBUD_PIDDIR"
    chown $KUBUD_USER:$KUBUD_GROUP "$KUBUD_CONFIGFILE"
    chmod 0660 "$KUBUD_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$KUBUD_PIDFILE" \
    --chuid $KUBUD_USER:$KUBUD_GROUP \
    --exec "$KUBUD_BIN" \
    -- \
    -pid="$KUBUD_PIDFILE" \
    -conf="$KUBUD_CONFIGFILE" \
    -datadir="$KUBUD_DATADIR" \
    -disablewallet \
    -daemon

